import 'package:flutter/material.dart';

import '../../models/item/item.dart';

class ItemProvider extends ChangeNotifier {
  ItemProvider() {
    _load();
  }
  Item item(String codeValue) {
    final int index =
        _items.indexWhere((Item element) => element.code == codeValue);
    return index < 0 ? _null : _items[index];
  }

  List<Item> _items = <Item>[];
  _load() {
    _items = <Item>[
      Item(
        id: '1',
        name: 'name1',
        code: 'code1',
        line: 'line1',
        category: 'category1',
        subCategory: 'subCategory1',
        formula: 'formula1',
        manufacturer: 'manufacturer1',
        supplier: 'supplier1',
        averagePrice: 111,
        discount: 1,
        quantity: 1111,
        salePrice: 1111,
      ),
      Item(
        id: '2',
        name: 'name2',
        code: 'code2',
        line: 'line1',
        category: 'category1',
        subCategory: 'subCategory1',
        formula: 'formula1',
        manufacturer: 'manufacturer1',
        supplier: 'supplier1',
        averagePrice: 121,
        discount: 2,
        quantity: 1211,
        salePrice: 1211,
      ),
      Item(
        id: '3',
        name: 'name3',
        code: 'code3',
        line: 'line1',
        category: 'category1',
        subCategory: 'subCategory1',
        formula: 'formula1',
        manufacturer: 'manufacturer1',
        supplier: 'supplier1',
        averagePrice: 131,
        discount: 3,
        quantity: 1311,
        salePrice: 1311,
      ),
      Item(
        id: '4',
        name: 'name4',
        code: 'code4',
        line: 'line1',
        category: 'category1',
        subCategory: 'subCategory1',
        formula: 'formula1',
        manufacturer: 'manufacturer1',
        supplier: 'supplier1',
        averagePrice: 141,
        discount: 4,
        quantity: 1411,
        salePrice: 1411,
      ),
      // 2
      Item(
        id: '20',
        name: 'name20',
        code: 'code20',
        line: 'line2',
        category: 'category2',
        subCategory: 'subCategory2',
        formula: 'formula2',
        manufacturer: 'manufacturer2',
        supplier: 'supplier2',
        averagePrice: 201,
        discount: 20,
        quantity: 2011,
        salePrice: 2011,
      ),
      Item(
        id: '21',
        name: 'name21',
        code: 'code21',
        line: 'line2',
        category: 'category2',
        subCategory: 'subCategory2',
        formula: 'formula2',
        manufacturer: 'manufacturer2',
        supplier: 'supplier2',
        averagePrice: 211,
        discount: 21,
        quantity: 2111,
        salePrice: 2111,
      ),
      Item(
        id: '22',
        name: 'name22',
        code: 'code22',
        line: 'line2',
        category: 'category2',
        subCategory: 'subCategory2',
        formula: 'formula2',
        manufacturer: 'manufacturer2',
        supplier: 'supplier2',
        averagePrice: 221,
        discount: 22,
        quantity: 2211,
        salePrice: 2211,
      ),
      Item(
        id: '23',
        name: 'name23',
        code: 'code23',
        line: 'line2',
        category: 'category2',
        subCategory: 'subCategory2',
        formula: 'formula2',
        manufacturer: 'manufacturer2',
        supplier: 'supplier2',
        averagePrice: 231,
        discount: 23,
        quantity: 2311,
        salePrice: 2311,
      ),
      // 3
      Item(
        id: '30',
        name: 'name30',
        code: 'code30',
        line: 'line3',
        category: 'category3',
        subCategory: 'subCategory3',
        formula: 'formula3',
        manufacturer: 'manufacturer3',
        supplier: 'supplier3',
        averagePrice: 301,
        discount: 30,
        quantity: 3011,
        salePrice: 3011,
      ),
      Item(
        id: '31',
        name: 'name31',
        code: 'code31',
        line: 'line3',
        category: 'category3',
        subCategory: 'subCategory3',
        formula: 'formula3',
        manufacturer: 'manufacturer3',
        supplier: 'supplier3',
        averagePrice: 311,
        discount: 31,
        quantity: 3111,
        salePrice: 3111,
      ),
      Item(
        id: '32',
        name: 'name32',
        code: 'code32',
        line: 'line3',
        category: 'category3',
        subCategory: 'subCategory3',
        formula: 'formula3',
        manufacturer: 'manufacturer3',
        supplier: 'supplier3',
        averagePrice: 321,
        discount: 32,
        quantity: 3211,
        salePrice: 3211,
      ),
      Item(
        id: '33',
        name: 'name33',
        code: 'code33',
        line: 'line3',
        category: 'category3',
        subCategory: 'subCategory3',
        formula: 'formula3',
        manufacturer: 'manufacturer3',
        supplier: 'supplier3',
        averagePrice: 331,
        discount: 33,
        quantity: 3311,
        salePrice: 3311,
      ),
      // 4
      Item(
        id: '40',
        name: 'name40',
        code: 'code40',
        line: 'line4',
        category: 'category4',
        subCategory: 'subCategory4',
        formula: 'formula4',
        manufacturer: 'manufacturer4',
        supplier: 'supplier4',
        averagePrice: 401,
        discount: 40,
        quantity: 4011,
        salePrice: 4011,
      ),
      Item(
        id: '41',
        name: 'name41',
        code: 'code41',
        line: 'line4',
        category: 'category4',
        subCategory: 'subCategory4',
        formula: 'formula4',
        manufacturer: 'manufacturer4',
        supplier: 'supplier4',
        averagePrice: 411,
        discount: 41,
        quantity: 4111,
        salePrice: 4111,
      ),
      Item(
        id: '42',
        name: 'name42',
        code: 'code42',
        line: 'line4',
        category: 'category4',
        subCategory: 'subCategory4',
        formula: 'formula4',
        manufacturer: 'manufacturer4',
        supplier: 'supplier4',
        averagePrice: 421,
        discount: 42,
        quantity: 4211,
        salePrice: 4211,
      ),
      Item(
        id: '43',
        name: 'name43',
        code: 'code43',
        line: 'line4',
        category: 'category4',
        subCategory: 'subCategory4',
        formula: 'formula4',
        manufacturer: 'manufacturer4',
        supplier: 'supplier4',
        averagePrice: 431,
        discount: 43,
        quantity: 4311,
        salePrice: 4311,
      ),
    ];
  }

  Item get _null => Item(
        id: 'null',
        name: 'null',
        code: 'null',
        line: 'null',
        category: 'null',
        subCategory: 'null',
        formula: 'null',
        manufacturer: 'null',
        supplier: 'null',
        averagePrice: 0,
        discount: 0,
        quantity: 0,
        salePrice: 0,
      );
}
